baseURL = "/"
languageCode = "en-gb"
title = "Breaker of Things"

cononifyurls = true

[pagination]
pageSize = 10

theme = "not-much"

pygmentsStyle = "native"
pygmentsCodeFences = true

[params]
github  = "LeoAdamek"
email   = "web-contact-2025.4@breakerofthings.email"
theme   = "dark"
palette   = "catpuccin"
copyright = "© {year}"
author.name = "Breaker of Things"

[[menu.main]]
  identifier = "posts"
  name = "posts"
  title = "blog"
  url = "/posts"

[[menu.main]]
  identifier = "github"
  name = "github"
  title = "github"
  url = "https://github.com/LeoAdamek"
