baseURL = "/"
languageCode = "en-gb"
title = "Breaker of Things"

cononifyurls = true

paginate = 3

theme = "not-much"


[author]
name = "Breaker of Things"

pygmentsStyle = "native"
pygmentsCodeFences = true

[params]
github  = "LeoAdamek"
email   = "web-contact-2025@breakerofthings.email"
theme   = "dark"
palette   = "catpuccin"
copyright = "© {year}"

[[menu.main]]
  identifier = "posts"
  name = "posts"
  title = "blog"
  url = "/posts"

[[menu.main]]
  identifier = "github"
  name = "github"
  title = "github"
  url = "https://github.com/LeoAdamek"
