baseURL = "/"
languageCode = "en-gb"
title = "Breaker of Things"

cononifyurls = true

paginate = 3

theme = "hugo-dusk"


[author]
name = "Breaker of Things"

pygmentsStyle = "native"
pygmentsCodeFences = true

[params]
github  = "LeoAdamek"
email   = "web-contact-2025@breakerofthings.email"

[params.colors]
  # hugo-dusk colors
  background = "#101010" # background color for the site
  main = "#99cc66"
  text = "#dbdbdb"
  code-quote-bg = "#1D1F21" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color
